# Generated by Django 5.2 on 2025-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testemunhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemunhos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='testemunhos/'),
        ),
        migrations.AlterField(
            model_name='testemunhos',
            name='texto_sobre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
