# Generated by Django 5.2 on 2025-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testemunhos_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
